import Head from "next/head";
import Link from "next/link";
import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { RouterOutputs, api } from "~/utils/api";
import Image from "next/image";

export default function Home() {
  const user = useUser();
  dayjs.extend(relativeTime);
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const { data, isLoading } = api.post.getAll.useQuery();

  type PostWithUSer = RouterOutputs["post"]["getAll"][number];
  const Postview = (props: PostWithUSer) => {
    const { post, author } = props;
    return (
      <div
        className=" flex flex-row gap-3 border-b border-slate-400 p-4"
        key={post.id}
      >
        <Image
          alt="profile pic"
          className="h-14 w-14 rounded-full "
          src={author.profileImageUrl}
          width={56}
          height={56}
        />
        <div className="flex flex-col ">
          <div className="flex gap-1 text-slate-300 ">
            <span>{"@" + author.username}</span>
            <span className="text-slate-400">
              {"• " + dayjs(post.createdAt).fromNow()}
            </span>
          </div>
          <span> {post.content}</span>
        </div>
      </div>
    );
  };

  const CreatePostWizard = () => {
    const { user } = useUser();
    console.log(user);
    if (!user) {
      return null;
    }
    return (
      <div className="flex w-full gap-4">
        <Image
          width={56}
          height={56}
          className="h-14 w-14 rounded-full"
          alt="Profile-image"
          src={user.imageUrl} 
        />
        <input
          className="grow bg-transparent outline-none"
          placeholder="Type Emoji's"
        />
      </div>
    );
  };

  if (isLoading) return <div>Loading..</div>;
  if (!data) return <div>something went wrong </div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen  justify-center ">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn ? (
              <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
            ) : (
              <CreatePostWizard />
            )}
          </div>{" "}
          <div className="flex flex-col">
            {data?.map(({ post, author }) => (
              <Postview post={post} author={author} key={post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
